export type RootStackParamList = {
  Login: undefined;
  Register: undefined;
  Home: undefined;
  AddTransaction: undefined;
  EditTransaction: { transactionId: string };
  Goals: undefined;
  AddGoal: undefined;
  GoalDetail: { goalId: string };
  EditGoal: { goalId: string };
  Budgets: undefined;
  AddBudget: undefined;
  EditBudget: { budgetId: string };
  Investments: undefined;
  AddInvestment: undefined;
  InvestmentDetail: { investmentId: string };
  AddInvestmentTransaction: { investmentId: string };
  Settings: undefined;
  EditProfile: undefined;
  PrevisaoFinanceira: undefined;
  AddGoalTransaction: { goalId: string };
};
